# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='idno',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
