# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-03 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_userprofileinfo_latest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='idno',
        ),
    ]
