# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_remove_userprofileinfo_idno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='latest',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='subscribed',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
